[workspace]
resolver = "2"
members = [
    "crates/pony_core",
    "src-tauri",
]

[workspace.package]
version = "0.1.1"
edition = "2024"
rust-version = "1.85"
authors = ["pony"]

[profile.dev]
opt-level = 1
debug = 1
incremental = true
codegen-units = 256
strip = "none"

[profile.release]
opt-level = 2
lto = "thin"
codegen-units = 1
strip = "symbols"
panic = "abort"

[profile.clean-dev]
inherits = "dev"
incremental = false
debug = false

[profile.ci]
inherits = "dev"
debug = false
incremental = false
